### PR TITLE
Add japanese

### PR DESCRIPTION
**Pull request by inductor**

### CODE REVIEW

**Comment by inductor** [comment]
@curtistimson ping

**Comment by curtistimson** [comment]
Thanks for the contribution @inductor !

I've made a few minor updates to the PR to include a change log record and README description.

However the PR is missing a few additional translations in the `data` folder. For example here is the French translation set:

https://github.com/curtistimson/hugo-theme-massively/tree/develop/exampleSite/data

**Comment by inductor** [comment]
Thanks! Added the folder :)

**Comment by inductor** [comment]
@curtistimson

**Comment by curtistimson** [comment]
Apologies about the late response - and thanks for making the updates.

I'll merge these changes into `develop` now so that they will form part of the next release! 😄

**Pull request merged**
