### PR TITLE
Add asset handling using Hugo Pipes

### LINKED ISSUE #35: Minify CSS
`main.css` is currently not minified in production.

Add gulp tasks to minify.

### PR DESCRIPTION
**Pull request by seshaljain**
Fixes #35 

Added a hugo pipes workflow to concatenate and minify `css` and `js` assets
Required moving assets to `assets/` directory

!Requires Hugo 0.43+ Extended

### CODE REVIEW

**Comment by seshaljain** [comment]
Also, using Hugo Pipes natively eliminates adding external Gulp workflows

**Comment by seshaljain** [comment]
Looks like Netlify still uses non-Extended versions of hugo, so the build would fail on netlify

Checking the `resources/` folder is a temporary workaround
netlify/binrc#17
netlify/build-image#182

**Comment by seshaljain** [comment]
On further investigation: 🕵️
[Netlify Blog: A more flexible build architecture with updated Linux](https://www.netlify.com/blog/2019/03/14/a-more-flexible-build-architecture-with-updated-linux/)

**Comment by curtistimson** [comment]
Apologies I'm late replying to this - thanks for the contribution!

Following your last commit, do you still think this will require changes in the Netlify control panel? It looks as though the build is passing successfully:

https://deploy-preview-80--hugo-theme-massively.netlify.com

**Comment by seshaljain** [comment]
No, committing the resources allows Hugo to prevent from building source files at build.
So, it should work on a standard Netlify setup.

Netlify is working towards allowing Hugo extended versions, so `resources` folder won't be required then.

**Comment by curtistimson** [comment]
Apologies for the delay @seshaljain.

I've approved / merged your changes, and finally been able to close #35 😄

Thanks again for the contribution!

**Pull request merged**
